# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CheckIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Intent:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CheckIntent", llm_response=llm_response, mode="request")
        return typing.cast(types.Intent, result)

    def Claritycheckfunction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClarityCheck:
        result = self.__options.merge_options(baml_options).parse_response(function_name="Claritycheckfunction", llm_response=llm_response, mode="request")
        return typing.cast(types.ClarityCheck, result)

    def DefineRoute(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Route:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DefineRoute", llm_response=llm_response, mode="request")
        return typing.cast(types.Route, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def FetchGLParams(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GLParams:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FetchGLParams", llm_response=llm_response, mode="request")
        return typing.cast(types.GLParams, result)

    def FetchResults(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Parameters:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FetchResults", llm_response=llm_response, mode="request")
        return typing.cast(types.Parameters, result)

    def InputGuardrail(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InputPromptCheck:
        result = self.__options.merge_options(baml_options).parse_response(function_name="InputGuardrail", llm_response=llm_response, mode="request")
        return typing.cast(types.InputPromptCheck, result)

    def SqlQueryGenerator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SqlQuery:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SqlQueryGenerator", llm_response=llm_response, mode="request")
        return typing.cast(types.SqlQuery, result)

    def SqlResult(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Response:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SqlResult", llm_response=llm_response, mode="request")
        return typing.cast(types.Response, result)

    def ValidateToolCalling(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Toolvalidation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateToolCalling", llm_response=llm_response, mode="request")
        return typing.cast(types.Toolvalidation, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def CheckIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Intent:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CheckIntent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Intent, result)

    def Claritycheckfunction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClarityCheck:
        result = self.__options.merge_options(baml_options).parse_response(function_name="Claritycheckfunction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClarityCheck, result)

    def DefineRoute(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Route:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DefineRoute", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Route, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def FetchGLParams(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GLParams:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FetchGLParams", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GLParams, result)

    def FetchResults(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Parameters:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FetchResults", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Parameters, result)

    def InputGuardrail(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InputPromptCheck:
        result = self.__options.merge_options(baml_options).parse_response(function_name="InputGuardrail", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InputPromptCheck, result)

    def SqlQueryGenerator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SqlQuery:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SqlQueryGenerator", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SqlQuery, result)

    def SqlResult(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Response:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SqlResult", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Response, result)

    def ValidateToolCalling(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Toolvalidation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateToolCalling", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Toolvalidation, result)

    