# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClarityCheck": types.ClarityCheck,
    "stream_types.ClarityCheck": stream_types.ClarityCheck,

    "types.ComponentDetail": types.ComponentDetail,
    "stream_types.ComponentDetail": stream_types.ComponentDetail,

    "types.Intent": types.Intent,
    "stream_types.Intent": stream_types.Intent,

    "types.Invocations": types.Invocations,
    "stream_types.Invocations": stream_types.Invocations,

    "types.Parameters": types.Parameters,
    "stream_types.Parameters": stream_types.Parameters,

    "types.Response": types.Response,
    "stream_types.Response": stream_types.Response,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.Route": types.Route,
    "stream_types.Route": stream_types.Route,

    "types.SqlQuery": types.SqlQuery,
    "stream_types.SqlQuery": stream_types.SqlQuery,

    "types.Toolvalidation": types.Toolvalidation,
    "stream_types.Toolvalidation": stream_types.Toolvalidation,


    "types.Tools": types.Tools,

}