# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class Tools(str, Enum):
    pass

# #########################################################################
# Generated classes (7)
# #########################################################################

class ClarityCheck(BaseModel):
    clarity: bool
    functioncall: typing.Optional[typing.List["Invocations"]] = None
    reasoning: typing.Optional[str] = None

class ComponentDetail(BaseModel):
    source: str
    crieteria: str
    risk: typing.Optional[str] = None

class Intent(BaseModel):
    valid: bool

class Invocations(BaseModel):
    tool_name: str
    parameters: typing.Union[typing.List[str], typing.List[int]]

class Parameters(BaseModel):
    components: typing.Dict[str, typing.List["ComponentDetail"]]
    formula: str
    planner: str
    sql_template: str

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class Toolvalidation(BaseModel):
    valid: bool
    tool_name: typing.Optional[typing.List[str]] = None
    description: typing.Optional[typing.List[str]] = None
    reasoning: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
